### ISSUE TITLE
Please disable the graphs animations

### ISSUE THREAD

**Issue by rgl** [talos-systems/theila#55]
Can you please disable the graphs animations? They take too long to appear and are very annoying generally speaking. To me of course :-D

For example, the animations that show at http://10.3.0.2:8080/node/10.3.0.100/overview?cluster=example&namespace=default&uid=35b40776-e593-401f-b9fd-ecfbc9dfed36:

![image](https://user-images.githubusercontent.com/43356/126074477-b8f9db94-18d9-4fa9-ab6a-4d40f3013cc4.png)

**Comment by andrewrynhard** [comment]
@rgl UIs are obviously hard to get right for everyone, but help me understand if there is a _techincal_ issue here outside of just not liking graphs? Also, what would "disabling" mean to you? The actual animation (i.e. updating of the graph) or the graphs altogether. What about the users that _do_ like it? How do we make everyone happy?

**Comment by rgl** [comment]
Oh, just the animations, the graph itself is very useful :-)

By disabling I mean, do not show any transition/animation, just show the graph at once.

But maybe there is something fubar at my side, because here, it takes about a second for the data to fully appear on the graph. 

Here is a similar effect https://www.chartjs.org/docs/latest/samples/line/line.html, where it animates the lines. If this is not clear, I'll try to make a video next week.

**Comment by Unix4ever** [comment]
Yeah, that makes sense. Only think worth mentioning is that is not an animation, it's the way we get all data from the server :)
As it's grpc stream we load points one by one.

I was thinking about aggregating these new point events into chunks. That should make it smoother.

**Comment by rgl** [comment]
Nice to known the reason. That sounds like it would make it smoother; showing the initial data in a single chunk :-)

Please note that this is nothing urgent, far from it, its just a pet peeve of mine. I will use it as-is anyways!
