### ISSUE TITLE
Servers labels/values seem to be swapped

### ISSUE THREAD

**Issue by rgl** [talos-systems/theila#56]
The labels/values seem to be swapped at the server page:

![image](https://user-images.githubusercontent.com/43356/126074583-bcbf1b91-fd0c-45e0-859a-9b4e68b6613e.png)

I think it should read `arch: amd64` instead of `amd64: arch`.

Also, please replace the collapse server icon from something that points upwards to something that points to the right side.

**Comment by Unix4ever** [comment]
Thanks. I'll fix the labels.
As of the button style it looks like it's common practice to have it as we have. Except I got it upside down:
https://i.pinimg.com/originals/62/f1/da/62f1da32967de421a054c9fe5b98b0cf.gif

**Comment by rgl** [comment]
Ah indeed. Got confused too. The ones you've showed is what I've wanted to say, but didn't! :-)

**Comment by rgl** [comment]
Are you also changing the ones in the left/side-panel (the one with the sidero ui main navigation menu)?
