### ISSUE TITLE
Clicking a server node fails to retrieve its data

### ISSUE THREAD

**Issue by rgl** [talos-systems/theila#57]
This is most probably a problem with my setup (running sidero in docker), but I'm not sure how to fix it.

The home page shows the node:

![image](https://user-images.githubusercontent.com/43356/126074947-eb825016-614e-4d77-9d25-1166b34da9f3.png)

But when I click it, it errors with:

![image](https://user-images.githubusercontent.com/43356/126074961-b5d8c3c0-3d7e-4b25-a8e2-b15f8c58ba03.png)

The same happens when I click `Services` and `Dmesg`.

Any idea why?

**Comment by andrewrynhard** [comment]
Looks like you haven't set the endpoints yet on your talosconfig?

**Comment by Unix4ever** [comment]
It may be that Theila can't find matching talosconfig in `~/.talos/config`.
I'm not happy with the way it works right now, but the only way to get talos config for the cluster is to check the `kubernetes` cluster context we are currently connected to and then find the cluster in `talos/config` with the same name.

Obviously, the error can be made more obvious as well. That's definitely in plans.

**Comment by rgl** [comment]
Thank you for pointing me in the right direction!

I failed to provide the talos configuration to the theila container!

After https://github.com/rgl/sidero-vagrant/commit/b81cbf32af01c56cecb67be4ccf9bdbcc08b7cca it now works :-)
