### ISSUE TITLE
Cannot reboot/reset a cluster node

### ISSUE THREAD

**Issue by rgl** [talos-systems/theila#65]
When I use the reboot or reset from:

![image](https://user-images.githubusercontent.com/43356/126834449-047d11d9-cd4a-44e7-b5d3-c89d57e2f992.png)

It shows this error window:

![image](https://user-images.githubusercontent.com/43356/126834549-a96e0773-5373-403d-8c34-932b321d410a.png)

This might be something with my environment, I'm using theila in container started as:

https://github.com/rgl/sidero-vagrant/blob/b7fe3493de569de4d8871e803f22fb59d063c844/provision-theila.sh#L10-L27

I've put the kubeconfig and talosconfig at https://gist.github.com/rgl/99c9a33a790dd6bfd3baa586c9b488f4

Any idea why this might be happening?

**Comment by Unix4ever** [comment]
It looks like it got correct endpoint, but incorrect certs. Is it the same for the other node?

So, your local talosconfig is not the one used in that request. It's actually pulling it from `talosconfig` kubernetes resource, which is stored in your management cluster.

You can also try opening clusters and hit Download Talos Config there.
Then check if you can connect to your cluster. If it works, then maybe we got some weird mix of talosconfigs in the reboot call.

I will spin up Sidero test cluster and see if it's reproduced later.

**Comment by rgl** [comment]
All the nodes return the same error.

I can connect to the cluster using the downloaded talosconfig from the ui.
